server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instance
          uri: "https://github.com/joelksk/microservice-sales.git"
          search-paths: config-data
  application:
    name: config-service
  
